name = "Gatchi Pack"
author = "Gatchi"
version = "0.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f8b158df13ff470d4c8448efcd6089afd2d86369b9b8276d3ce8fcad5a0fa4b"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
