name = "Gatchi Pack"
author = "Gatchi"
version = "0.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "54f2b48629164a47f9050494f7df20e68944e48182ee5d1311cad844768f6ad3"

[versions]
fabric = "0.14.14"
minecraft = "1.18.2"
