name = "Gatchi Pack"
author = "Gatchi"
version = "0.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "81090b1b9779c04546ab6f7b548880e97c0a165efa0b52bf5a89d2a638b99c08"

[versions]
fabric = "0.14.14"
minecraft = "1.18.2"
