name = "Gatchi Pack"
author = "Gatchi"
version = "0.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "36fdb1f6235e0981db0482a353e23bbb2f5c7f782e0c1019b41cb062e763cc91"

[versions]
fabric = "0.14.14"
minecraft = "1.18.2"
