name = "Gatchi Pack"
author = "Gatchi"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1628049bd07e460d087d573e4d06b869c229734605f2e41339ea5b84d328943c"

[versions]
fabric = "0.14.14"
minecraft = "1.18.2"
