name = "Gatchi Pack"
author = "Gatchi"
version = "0.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bca8f0b7627644493c78eca93a1c0d869830d533020200f385c7f8d65ead52a0"

[versions]
fabric = "0.14.14"
minecraft = "1.18.2"
