name = "Gatchi Pack"
author = "Gatchi"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2327432b3fec471febadf8925d9cab82352ba0b27b1997a979b7fa078428f645"

[versions]
fabric = "0.14.14"
minecraft = "1.18.2"
