name: Create Archive

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Fetch Version
        id: version
        run: echo ::set-output name=version::$(cat "version")

      - name: Archive Release Contents
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'release.zip'
          exclusions: '*.git*'

      - name: Upload Release Artifacts
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: 'release.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}