name: Package
on: [push]

jobs:
  mods:
    name: Package Mods
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: oracle
          java-version: 17
          java-package: jdk

      - name: Serve toml files
        uses: Eun/http-server-action@v1
        with:
          directory: ${{ github.workspace }}
          port: 8080
          no-cache: true
          content-types: |
            { "toml": "text/plain" }

      - name: Get server mods
        run: |
          mkdir server && cd server
          java -jar ../packwiz-installer-bootstrap.jar -g -s server http://localhost:8080/pack.toml

      - name: Get client mods
        run: |
          mkdir client && cd client
          java -jar ../packwiz-installer-bootstrap.jar -g -s both http://localhost:8080/pack.toml

      - name: Upload server mods
        uses: actions/upload-artifact@v3
        with:
          name: server-mods
          path: server/

      - name: Upload client mods
        uses: actions/upload-artifact@v3
        with:
          name: client-mods
          path: client/
  test:
    name: Test Server & Generate Config
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download server mods
        uses: actions/download-artifact@v3
        with:
          name: server-mods
          path: server/

      - name: Run server
        run: |
        docker run -v $(pwd)/server:/data -e TYPE=FABRIC -e VERSION=1.18.2 -e ENABLE_AUTOSTOP=TRUE -e AUTOSTOP_TIMEOUT_INIT=1 -e EULA=TRUE -e
MEMORY=4G itzg/minecraft-server

      - name: Check server folder
        run: ls server
