name: Create Archive

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Fetch Version
        id: version
        run: echo ::set-output name=version::$(cat "version")

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.version }}
          release_name: Release ${{ steps.version.outputs.version }}
          draft: false
          prerelease: false

      - name: Archive Release Contents
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'release.zip'
          exclusions: '*.git*'

      - name: Upload Release Artifacts
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: 'release.zip'
          token: ${{ secrets.GITHUB_TOKEN }}